name: Build PostGIS Docker Image

on:
  watch:
    types: [started]
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date '+%Y.%m.%d.%H.%M%S')" >> $GITHUB_ENV
      - name: Log timestamp
        run: echo "Current timestamp ${{ env.TIMESTAMP }}"

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: postgis.16-3.4.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            dextercai/postgis:16-3.4
            