name: Crop PMTiles

on:
  workflow_dispatch:
    inputs:
      from:
        description: 'From'
        required: true
        default: 'https://build.protomaps.com/20250521.pmtiles'
      label:
        description: 'Label'
        required: true
        default: 'latest'
      maxzoom:
        description: 'MaxZoom'
        required: true
        default: '14'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.cnb.cool
        username: ${{ secrets.CNB_DOCKER_AK }}
        password: ${{ secrets.CNB_DOCKER_SK }}

    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: protomap/runtime.dockerfile
        platforms: linux/amd64
        build-args: |
          FROM=${{ github.event.inputs.from }}
          MAXZOOM=${{ github.event.inputs.maxzoom }}
        push: true
        tags: |
          docker.cnb.cool/dextercai/docker_public/proto-basemap:${{ github.event.inputs.label }}
            
