name: PullAndPush

on:
  workflow_dispatch:
    inputs:
      from:
        description: 'From'
        required: true
        default: 'busybox'
      to:
        description: 'To'
        required: true
        default: 'dextercai/busybox'
      arch:
        description: 'Arch'
        required: true
        default: 'linux/amd64,linux/arm64'

jobs:
  pull_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          region: cn-east-3
          access-key-id: ${{ secrets.HWCLOUD_AK }}
          access-key-secret: ${{ secrets.HWCLOUD_SK }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.cnb.cool
          username: ${{ secrets.CNB_DOCKER_AK }}
          password: ${{ secrets.CNB_DOCKER_SK }}

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Gen Dockerfile
      #   id: gen-dockefile
      #   run: |
      #     cat << EOF > pull-and-push.dockerfile 
      #     FROM ${{ github.event.inputs.from }}
      #     EOF
      
      # - name: Build and push
      #   uses: docker/build-push-action@v5.0.0
      #   with:
      #     context: .
      #     file: pull-and-push.dockerfile
      #     platforms: ${{ github.event.inputs.arch }}
      #     push: true
      #     tags: |
      #       ${{ github.event.inputs.to }}
      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ${{ github.event.inputs.to }} \
            ${{ github.event.inputs.from }}
          