name: Build UDPXY Docker Image

on:
  watch:
    types: [started]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2

      - name: Set timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date '+%Y.%m.%d.%H.%M%S')" >> $GITHUB_ENV
      - name: Log timestamp
        run: echo "Current timestamp ${{ env.TIMESTAMP }}"

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: udpxy.dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            dextercai/udpxy:latest
            dextercai/udpxy:${{ env.TIMESTAMP }}
            

# name: build udpxy

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         id: qemu
#         uses: docker/setup-qemu-action@v1
#       - name: checkout code
#         uses: actions/checkout@v2
#       - name: install buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v1
#         with:
#           version: latest
#       - name: login to docker hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#       - name: build the image
#         run: |
#           docker buildx build --push \
#             --tag dextercai/udpxy:latest \
#             --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .