name: Build WVP Pro Docker Image Source

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build-wvp28181-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date '+%Y.%m.%d.%H.%M%S')" >> $GITHUB_ENV
    - name: Log timestamp
      run: echo "Current timestamp ${{ env.TIMESTAMP }}"

    - name: Log in to DockerHub Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: wvp/wvp-gb28281.dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          dextercai/wvp_pro:${{ env.TIMESTAMP }}
          dextercai/wvp_pro:latest
 